### ISSUE TITLE
GitHub for projects 

### ISSUE THREAD

**Issue by maurolepore** [si-library/meetups#1]
* Speaker: Mauro Lepore
* Contact: 
   * GitHub @maurolepore
   * Profile: bit.ly/mauro-lepore
   * Other: https://twitter.com/mauro_lepore
* Links: https://bit.ly/github-for-projects
* Details:

![](https://i.imgur.com/60IA0qz.png)

![](https://i.imgur.com/TdFODNn.png)

**Comment by maurolepore** [comment]
Thanks everyone for attending. 

To ask me questions, refer to me as @maurolepore.

Cheers,
Mauro

**Comment by bullardk** [comment]
Hi @maurolepore ! This has great potential. A challenge I've been looking for solutions for is finding a way to manage registrations, sign-ins and follow-ups. The SI Moodle is limiting because it is quite bloated and is limited to only people on the SI network. Is it possible for people to sign up for a training session and participate in a discussion without creating a GitHub account?

~K

**Comment by maurolepore** [comment]
@bullardk, in my opinion, the simplest, coherent system is that of google. This system is likely going to be the focus of my next talk. (I briefly discussed it with Paola from STRI and she seems interested.)

People could register via a [Google Form](https://www.google.com/intl/en-GB/forms/about/) -- even if they lack a google account. The form internally feeds a Google Sheet, that you can keep through time, and analyze. 

For live discussion, you can share a Google doc, that you can use to share the important links and to gather questions live. This works even for people without google accounts -- no login required. For example, the doc I use for this is always the same: http://bit.ly/mauro-doc
